server:
  port: 9000

spring:
  application:
    name: vn-practica03
  datasource:
    url: jdbc:h2:file:./data/h2/db/practica03-db
    username: practica03
    password: 123
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
    show-sql: true

logging:
  level:
    root: INFO
    sql: TRACE
