CREATE TABLE ACTOR(
	ID_ACTOR BIGINT PRIMARY KEY,
	NOMBRE VARCHAR(150),
	EDAD INTEGER,
	NACIONALIDAD VARCHAR(150)
);

CREATE TABLE DIRECTOR(
	ID_DIRECTOR BIGINT PRIMARY KEY,
	NOMBRE VARCHAR(150),
	EDAD INTEGER,
	NACIONALIDAD VARCHAR(150)
);

CREATE TABLE PRODUCTORA(
	ID_PRODUCTORA BIGINT PRIMARY KEY,
	NOMBRE VARCHAR(150),
	ANIO_FUNDACION INTEGER
);


CREATE TABLE SERIE(
	ID_SERIE BIGINT PRIMARY KEY,
	TITULO VARCHAR(150),
	ANIO INTEGER,
	ID_ACT BIGINT REFERENCES ACTOR(ID_ACTOR),
	ID_DIR BIGINT REFERENCES DIRECTOR(ID_DIRECTOR),
	ID_PRO BIGINT REFERENCES PRODUCTORA(ID_PRODUCTORA)

	
);


CREATE TABLE PELICULA(
	ID_PELICULA BIGINT PRIMARY KEY,
	TITULO VARCHAR(150),
	ANIO INTEGER,
	ID_DIR BIGINT REFERENCES DIRECTOR(ID_DIRECTOR),
	ID_PRO BIGINT REFERENCES PRODUCTORA(ID_PRODUCTORA),
	ID_ACT BIGINT REFERENCES ACTOR(ID_ACTOR)
);