spring:
  datasource:
    url: jdbc:h2:file:/demo/data
    username: user
    password: 1234
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

logging:
  level:
    root: ERROR
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE