batch01:
  tramo-input-file: tramos_calle_BarrioDismuniOneMillion.csv
  output-folder-path: out/


spring:
  application:
    name: vn-practica05
  profiles:
    active:
      - dev

logging:
  level:
    root: INFO
    com.viewnext: INFO
