batch01:
  district_filter:
    district: ESTE
    tramo-input-file: tramos_calle_BarrioDismuniOneMillion.csv
  db_dump:
    district-source-collection: district_filter-ESTE-1716539816011
    output-folder-path: out/


spring:
  application:
    name: vn-practica05
  profiles:
    active:
      - dev

logging:
  level:
    root: INFO
    com.viewnext: INFO
