spring:
  application:
    name: vn-practica05-dev
  datasource:
    url: jdbc:h2:file:./data/h2/db/bsan-practica05
    username: practica05
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
