Spring:
  kafka:
    bootstrap-servers: localhost:9092
    key-deserializer: org.springframework.kafka.support.serializer.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.StringDeserializer
    consumer:
      auto-offset-reset: earliest
      group-id: baeldung
    test:
      topic: embedded-test-topic