CREATE SEQUENCE PRODUCER_SEQ
START WITH 1
INCREMENT BY 50;

CREATE SEQUENCE PRODUCTION_SEQ
START WITH 1
INCREMENT BY 50;

CREATE SEQUENCE WORKER_SEQ
START WITH 1
INCREMENT BY 50;

CREATE TABLE ACTOR (
  ID BIGINT NOT NULL PRIMARY KEY
);

CREATE TABLE DIRECTOR (
  ID BIGINT NOT NULL PRIMARY KEY
);

CREATE TABLE FILM (
  ID BIGINT NOT NULL PRIMARY KEY
);

CREATE TABLE PRODUCER (
  FOUNDATION_YEAR INTEGER NOT NULL,
  ID BIGINT NOT NULL PRIMARY KEY,
  NAME VARCHAR(255)
);

CREATE TABLE PRODUCTION (
  RELEASE_YEAR INTEGER NOT NULL,
  DIRECTOR_ID BIGINT,
  ID BIGINT NOT NULL PRIMARY KEY,
  PRODUCER_ID BIGINT,
  TITLE VARCHAR(255)
);

CREATE TABLE PRODUCTION_ACTOR (
  ACTOR_ID BIGINT NOT NULL,
  PRODUCTION_ID BIGINT NOT NULL
);

CREATE TABLE SERIE (
  ID BIGINT NOT NULL PRIMARY KEY
);

CREATE TABLE WORKER (
  AGE INTEGER NOT NULL,
  ID BIGINT NOT NULL PRIMARY KEY,
  NAME VARCHAR(255),
  NATIONALITY VARCHAR(255)
);

ALTER TABLE PRODUCTION_ACTOR
ADD CONSTRAINT FK_PRODUCTION_ACTOR_ACTOR
FOREIGN KEY (ACTOR_ID) REFERENCES ACTOR(ID);

ALTER TABLE DIRECTOR
ADD CONSTRAINT FK_DIRECTOR_WORKER
FOREIGN KEY (ID) REFERENCES WORKER(ID);

ALTER TABLE FILM
ADD CONSTRAINT FK_FILM_PRODUCTION
FOREIGN KEY (ID) REFERENCES PRODUCTION(ID);

ALTER TABLE ACTOR
ADD CONSTRAINT FK_ACTOR_WORKER
FOREIGN KEY (ID) REFERENCES WORKER(ID);

ALTER TABLE PRODUCTION
ADD CONSTRAINT FK_PRODUCTION_DIRECTOR
FOREIGN KEY (DIRECTOR_ID) REFERENCES DIRECTOR(ID);

ALTER TABLE PRODUCTION_ACTOR
ADD CONSTRAINT FK_PRODUCTION_ACTOR_PRODUCTION
FOREIGN KEY (PRODUCTION_ID) REFERENCES PRODUCTION(ID);

ALTER TABLE SERIE
ADD CONSTRAINT FK_SERIE_PRODUCTION
FOREIGN KEY (ID) REFERENCES PRODUCTION(ID);

ALTER TABLE PRODUCTION
ADD CONSTRAINT FK_PRODUCTION_PRODUCER
FOREIGN KEY (PRODUCER_ID) REFERENCES PRODUCER(ID);
