DROP TABLE tramos_calle IF EXISTS;

CREATE TABLE tramos_calle(
    CALLE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_CALLE BIGINT,
    TIPO_VIA VARCHAR(100),
    NOMBRE_CALLE VARCHAR(200),
    PRIMER_NUM_TRAMO INTEGER,
    ULTIMO_NUM_TRAMO INTEGER,
    BARRIO VARCHAR(200),
    COD_DISTRITO INTEGER,
    NOM_DISTRITO VARCHAR(200)
);