CREATE TABLE TRAMO_CALLE (
  CODIGO_CALLE INT,
  TIPO_VIA VARCHAR(255),
  NOMBRE_CALLE VARCHAR(255),
  PRIMER_NUM_TRAMO INT,
  ULTIMO_NUM_TRAMO INT,
  BARRIO VARCHAR(255),
  COD_DISTRITO INT,
  NOM_DISTRITO VARCHAR(255)
);